### ISSUE TITLE
Fix code scanning alert - Module-level cyclic import

### ISSUE THREAD

**Issue by rafskov** [rafskov/trashappDEMO#3]
I don't understand this alert. I thought models had to be imported after db in app.py.  At this same time, I'm getting import errors when trying to run locally:

```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/mnt/c/Users/rskov/OneDrive/Documents/Projects/trashappDemo/trashapp/trashvenv/lib/python3.6/site-packages/flask/cli.py", line 260, in locate_app
    __import__(module_name)
  File "/mnt/c/Users/rskov/OneDrive/Documents/Projects/trashappDemo/trashapp/app.py", line 18, in <module>
    from models import Post
  File "/mnt/c/Users/rskov/OneDrive/Documents/Projects/trashappDemo/trashapp/models.py", line 1, in <module>
    from app import db
ImportError: cannot import name 'db'

```

Tracking issue for:
- [ ] https://github.com/rafskov/trashappDEMO/security/code-scanning/2

**Comment by PrettyPrinted** [comment]
Generally, you don't want to have circular references like that, i.e. module A imports something from module B and module B imports something from module B.

In Flask, there are a couple of patterns to prevent this. First is the create_app pattern and second is the init_app pattern. 

I have an example here: https://github.com/PrettyPrinted/youtube_video_code/tree/master/2022/02/02/How%20to%20Use%20Flask-SQLAlchemy%20With%20Flask%20Blueprints/sqlalchemy_blueprint/myproject

Check out the __init__.py and the extensions.py for how this works.

If you want, we can make the first thing you submit as a pull request. Your code wouldn't have be to changed too much.
